name = "PhysicalTrees"
uuid = "dc5d4990-50a5-4af2-bdaa-6f78dc9b9fb2"
license = "GPLv3"
authors = ["islent <leoislent@gmail.com>"]
repository = "https://github.com/JuliaAstroSim/PhysicalTrees.jl"
version = "0.1.2"

[deps]
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ParallelOperations = "09c1cff2-b94d-4c31-85a1-721512e21c63"
PhysicalParticles = "78724250-4eb2-11e9-0f34-13a7aab864c5"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"

[compat]
BangBang = "0.3"
ParallelOperations = "0.1"
PhysicalParticles = "1"
Reexport = "1"
StaticArrays = "1"
StructArrays = "0.6"
Unitful = "1"
UnitfulAstro = "1"
julia = "1.6"
